import pyautogui as py
import time as ti

emailProfessor = "prof.humbertoLToledo@gmail.com"
email = input("DIGITE SEU EMAIL: ")
senha = input("SENHA DO EMAIL :")
ti.sleep(2.0)

ti.sleep(0.5)
py.press('winleft')
ti.sleep(1)
py.write('firefox')
ti.sleep(1)
py.press('enter')
ti.sleep(2)
py.hotkey('ctrl', 'shift', 'p')
py.press('enter')
py.press('F11')
py.write('https://gmail.com', interval=0.2)
ti.sleep(4.0)
py.press('enter')
ti.sleep(45)
py.write(email, interval=0.02)
py.press('enter')
ti.sleep(20)
py.write(senha, interval=0.1)
py.press('enter')
ti.sleep(35)
py.moveTo(90, 120)
py.click()
ti.sleep(10)
py.write(emailProfessor)
ti.sleep(10)
py.press('tab')
py.write('ATIVIDADE 01')
ti.sleep(10)
py.press('tab')
py.write('E aí Professor, Conseguimos!!! Aluno: PEDRO VINICIUS DE JESUS LIMA')
ti.sleep(5)
py.moveTo(815, 990)
py.click()
ti.sleep(5)
py.moveTo(330, 60)
py.doubleClick()
py.hotkey('ctrl', 'a')
ti.sleep(3)
py.write(r'F:\Fatec\automacao_python')
py.press('enter')
py.moveTo(230, 413)
py.doubleClick()
py.write("automacao.py", interval=0.02)
ti.sleep(2)
py.press('enter')
ti.sleep(5)
py.hotkey('ctrl', 'enter')
ti.sleep(15)
py.alert('ACABOU')